# Generated by Django 2.0 on 2018-12-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
