# Generated by Django 2.0 on 2018-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.ManyToManyField(to='one.Article'),
        ),
    ]
