# Generated by Django 2.0 on 2019-01-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=4)),
                ('password', models.IntegerField()),
                ('telephone', models.IntegerField()),
            ],
        ),
    ]
