# Generated by Django 2.0 on 2018-12-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='time',
            table='sunset',
        ),
    ]
