# Generated by Django 2.0 on 2018-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_auto_20181210_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['create_time', 'telephone']},
        ),
        migrations.AddField(
            model_name='time',
            name='telephone',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
