# Generated by Django 2.0 on 2018-12-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun', to='two.Front'),
        ),
    ]
