# Generated by Django 2.0 on 2019-01-01 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('pages', models.IntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('password', models.IntegerField()),
                ('telephone', models.IntegerField(validators=[django.core.validators.RegexValidator('1[345678]\\d{9}')])),
            ],
        ),
    ]
